env:
  global:
  # websockets only works on Python >= 3.4.
    - CIBW_SKIP="cp27-* cp33-*"
    - CIBW_TEST_COMMAND="python3 -W default -m unittest websockets"
    - WEBSOCKETS_TESTS_TIMEOUT_FACTOR=100

matrix:
  include:
    - dist: trusty
      sudo: required
      language: python
      python: "3.6"
      services:
        - docker
    - os: osx
      osx_image: xcode8.3

install:
# Python 3 is needed to run cibuildwheel for websockets.
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
      brew update;
      brew upgrade python;
    fi
# Install cibuildwheel using pip3 to make sure Python 3 is used.
  - pip3 install --upgrade cibuildwheel
# Create file '.cibuildwheel' so that extension build is not optional (c.f. setup.py).
  - touch .cibuildwheel

script:
  - cibuildwheel --output-dir wheelhouse
# Upload to PyPI on tags
  - if [ "${TRAVIS_TAG:-}" != "" ]; then
      pip3 install twine;
      python3 -m twine upload --skip-existing wheelhouse/*;
    fi
